// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.11.4
// source: idl/nested.proto

package example

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []string         `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	HasSub   bool             `protobuf:"varint,2,opt,name=hasSub,proto3" json:"hasSub,omitempty"`
	Value    []int32          `protobuf:"varint,3,rep,packed,name=value,proto3" json:"value,omitempty"`
	Extra    map[string]int32 `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SubItems []*Item          `protobuf:"bytes,5,rep,name=subItems,proto3" json:"subItems,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_nested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_idl_nested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_idl_nested_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Item) GetHasSub() bool {
	if x != nil {
		return x.HasSub
	}
	return false
}

func (x *Item) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item) GetExtra() map[string]int32 {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Item) GetSubItems() []*Item {
	if x != nil {
		return x.SubItems
	}
	return nil
}

type NestedExampleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *NestedExampleReq) Reset() {
	*x = NestedExampleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_nested_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedExampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedExampleReq) ProtoMessage() {}

func (x *NestedExampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_nested_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedExampleReq.ProtoReflect.Descriptor instead.
func (*NestedExampleReq) Descriptor() ([]byte, []int) {
	return file_idl_nested_proto_rawDescGZIP(), []int{1}
}

func (x *NestedExampleReq) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type NestedExampleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *NestedExampleResp) Reset() {
	*x = NestedExampleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_nested_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedExampleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedExampleResp) ProtoMessage() {}

func (x *NestedExampleResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_nested_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedExampleResp.ProtoReflect.Descriptor instead.
func (*NestedExampleResp) Descriptor() ([]byte, []int) {
	return file_idl_nested_proto_rawDescGZIP(), []int{2}
}

func (x *NestedExampleResp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_idl_nested_proto protoreflect.FileDescriptor

var file_idl_nested_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x6c, 0x2f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x70, 0x62, 0x33, 0x22, 0xd1, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x53, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x68, 0x61, 0x73, 0x53, 0x75, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a,
	0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x62, 0x33, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x25, 0x0a, 0x08, 0x73, 0x75,
	0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x33, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x73, 0x75, 0x62, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x33, 0x0a, 0x10, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x33, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x34, 0x0a, 0x11, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x43, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x38, 0x0a, 0x07, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x33, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x33, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x3e, 0x5a, 0x3c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77,
	0x65, 0x67, 0x6f, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x67, 0x6f, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_idl_nested_proto_rawDescOnce sync.Once
	file_idl_nested_proto_rawDescData = file_idl_nested_proto_rawDesc
)

func file_idl_nested_proto_rawDescGZIP() []byte {
	file_idl_nested_proto_rawDescOnce.Do(func() {
		file_idl_nested_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_nested_proto_rawDescData)
	})
	return file_idl_nested_proto_rawDescData
}

var file_idl_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_nested_proto_goTypes = []interface{}{
	(*Item)(nil),              // 0: pb3.Item
	(*NestedExampleReq)(nil),  // 1: pb3.NestedExampleReq
	(*NestedExampleResp)(nil), // 2: pb3.NestedExampleResp
	nil,                       // 3: pb3.Item.ExtraEntry
}
var file_idl_nested_proto_depIdxs = []int32{
	3, // 0: pb3.Item.extra:type_name -> pb3.Item.ExtraEntry
	0, // 1: pb3.Item.subItems:type_name -> pb3.Item
	0, // 2: pb3.NestedExampleReq.items:type_name -> pb3.Item
	0, // 3: pb3.NestedExampleResp.items:type_name -> pb3.Item
	1, // 4: pb3.Service.Example:input_type -> pb3.NestedExampleReq
	2, // 5: pb3.Service.Example:output_type -> pb3.NestedExampleResp
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_idl_nested_proto_init() }
func file_idl_nested_proto_init() {
	if File_idl_nested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_nested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_nested_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedExampleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_nested_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedExampleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_nested_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_nested_proto_goTypes,
		DependencyIndexes: file_idl_nested_proto_depIdxs,
		MessageInfos:      file_idl_nested_proto_msgTypes,
	}.Build()
	File_idl_nested_proto = out.File
	file_idl_nested_proto_rawDesc = nil
	file_idl_nested_proto_goTypes = nil
	file_idl_nested_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type Service interface {
	Example(ctx context.Context, req *NestedExampleReq) (res *NestedExampleResp, err error)
}
