// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f64toa = 752
    _entry__format_significand = 52800
    _entry__format_integer = 4000
    _entry__hm_get = 33568
    _entry__i64toa = 4432
    _entry__u64toa = 4704
    _entry__j2t_fsm_exec = 46576
    _entry__advance_ns = 16640
    _entry__fsm_exec = 23984
    _entry__advance_string = 19008
    _entry__validate_string = 26144
    _entry__utf8_validate = 27264
    _entry__skip_number = 22512
    _entry__j2t_number = 40288
    _entry__vnumber = 19856
    _entry__atof_eisel_lemire64 = 13792
    _entry__atof_native = 15840
    _entry__decimal_to_f64 = 14272
    _entry__left_shift = 53280
    _entry__right_shift = 53824
    _entry__j2t_string = 40880
    _entry__unquote = 9040
    _entry__unhex16_is = 11408
    _entry__j2t_binary = 41760
    _entry__b64decode = 29872
    _entry__j2t_field_vm = 43408
    _entry__tb_write_string = 35344
    _entry__tb_write_default_or_empty = 37312
    _entry__j2t_write_unset_fields = 39632
    _entry__j2t_key = 44576
    _entry__j2t_find_field_key = 42736
    _entry__quote = 6256
    _entry__tb_skip = 51744
    _entry__tb_write_i64 = 35216
    _entry__trie_get = 34448
)

const (
    _stack__f64toa = 80
    _stack__format_significand = 24
    _stack__format_integer = 16
    _stack__hm_get = 24
    _stack__i64toa = 16
    _stack__u64toa = 8
    _stack__j2t_fsm_exec = 632
    _stack__advance_ns = 16
    _stack__fsm_exec = 176
    _stack__advance_string = 48
    _stack__validate_string = 88
    _stack__utf8_validate = 32
    _stack__skip_number = 40
    _stack__j2t_number = 296
    _stack__vnumber = 240
    _stack__atof_eisel_lemire64 = 40
    _stack__atof_native = 136
    _stack__decimal_to_f64 = 80
    _stack__left_shift = 24
    _stack__right_shift = 16
    _stack__j2t_string = 184
    _stack__unquote = 112
    _stack__unhex16_is = 8
    _stack__j2t_binary = 216
    _stack__b64decode = 144
    _stack__j2t_field_vm = 312
    _stack__tb_write_string = 8
    _stack__tb_write_default_or_empty = 16
    _stack__j2t_write_unset_fields = 120
    _stack__j2t_key = 400
    _stack__j2t_find_field_key = 64
    _stack__quote = 72
    _stack__tb_skip = 48
    _stack__tb_write_i64 = 8
    _stack__trie_get = 32
)

const (
    _size__f64toa = 3248
    _size__format_significand = 480
    _size__format_integer = 432
    _size__hm_get = 544
    _size__i64toa = 272
    _size__u64toa = 1408
    _size__j2t_fsm_exec = 4640
    _size__advance_ns = 784
    _size__fsm_exec = 1332
    _size__advance_string = 800
    _size__validate_string = 1120
    _size__utf8_validate = 480
    _size__skip_number = 1300
    _size__j2t_number = 548
    _size__vnumber = 1600
    _size__atof_eisel_lemire64 = 416
    _size__atof_native = 608
    _size__decimal_to_f64 = 1568
    _size__left_shift = 544
    _size__right_shift = 464
    _size__j2t_string = 880
    _size__unquote = 2368
    _size__unhex16_is = 144
    _size__j2t_binary = 224
    _size__b64decode = 2864
    _size__j2t_field_vm = 1124
    _size__tb_write_string = 656
    _size__tb_write_default_or_empty = 936
    _size__j2t_write_unset_fields = 656
    _size__j2t_key = 1968
    _size__j2t_find_field_key = 384
    _size__quote = 2736
    _size__tb_skip = 972
    _size__tb_write_i64 = 64
    _size__trie_get = 336
)

var (
    _pcsp__f64toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {3176, 56},
        {3180, 48},
        {3181, 40},
        {3183, 32},
        {3185, 24},
        {3187, 16},
        {3189, 8},
        {3193, 0},
        {3248, 56},
    }
    _pcsp__format_significand = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {468, 24},
        {469, 16},
        {471, 8},
        {473, 0},
    }
    _pcsp__format_integer = [][2]uint32{
        {1, 0},
        {4, 8},
        {412, 16},
        {413, 8},
        {414, 0},
        {423, 16},
        {424, 8},
        {426, 0},
    }
    _pcsp__hm_get = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {531, 24},
        {532, 16},
        {534, 8},
        {536, 0},
    }
    _pcsp__i64toa = [][2]uint32{
        {1, 0},
        {171, 8},
        {172, 0},
        {207, 8},
        {208, 0},
        {222, 8},
        {223, 0},
        {247, 8},
        {248, 0},
        {253, 8},
        {259, 0},
    }
    _pcsp__u64toa = [][2]uint32{
        {13, 0},
        {162, 8},
        {163, 0},
        {175, 8},
        {240, 0},
        {498, 8},
        {499, 0},
        {519, 8},
        {592, 0},
        {852, 8},
        {928, 0},
        {1376, 8},
        {1378, 0},
    }
    _pcsp__j2t_fsm_exec = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {142, 184},
        {175, 192},
        {176, 200},
        {185, 208},
        {193, 216},
        {194, 224},
        {201, 232},
        {683, 184},
        {716, 192},
        {718, 200},
        {727, 208},
        {735, 216},
        {736, 224},
        {743, 232},
        {902, 184},
        {919, 192},
        {925, 200},
        {1564, 184},
        {1585, 192},
        {1592, 200},
        {3558, 184},
        {3565, 48},
        {3566, 40},
        {3568, 32},
        {3570, 24},
        {3572, 16},
        {3574, 8},
        {3578, 0},
        {4640, 184},
    }
    _pcsp__advance_ns = [][2]uint32{
        {1, 0},
        {4, 8},
        {716, 16},
        {717, 8},
        {718, 0},
        {745, 16},
        {746, 8},
        {747, 0},
        {771, 16},
    }
    _pcsp__fsm_exec = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1091, 88},
        {1095, 48},
        {1096, 40},
        {1098, 32},
        {1100, 24},
        {1102, 16},
        {1104, 8},
        {1105, 0},
        {1332, 88},
    }
    _pcsp__advance_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {314, 48},
        {315, 40},
        {317, 32},
        {319, 24},
        {321, 16},
        {323, 8},
        {327, 0},
        {787, 48},
    }
    _pcsp__validate_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {482, 56},
        {486, 48},
        {487, 40},
        {489, 32},
        {491, 24},
        {493, 16},
        {495, 8},
        {499, 0},
        {1107, 56},
    }
    _pcsp__utf8_validate = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {467, 32},
        {468, 24},
        {470, 16},
        {472, 8},
        {480, 0},
    }
    _pcsp__skip_number = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {1253, 40},
        {1254, 32},
        {1256, 24},
        {1258, 16},
        {1260, 8},
        {1264, 0},
        {1300, 40},
    }
    _pcsp__j2t_number = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {531, 56},
        {535, 48},
        {536, 40},
        {538, 32},
        {540, 24},
        {542, 16},
        {544, 8},
        {548, 0},
    }
    _pcsp__vnumber = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {145, 104},
        {149, 48},
        {150, 40},
        {152, 32},
        {154, 24},
        {156, 16},
        {158, 8},
        {159, 0},
        {1595, 104},
    }
    _pcsp__atof_eisel_lemire64 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {322, 40},
        {323, 32},
        {325, 24},
        {327, 16},
        {329, 8},
        {330, 0},
        {394, 40},
    }
    _pcsp__atof_native = [][2]uint32{
        {1, 0},
        {4, 8},
        {596, 56},
        {600, 8},
        {602, 0},
    }
    _pcsp__decimal_to_f64 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1525, 56},
        {1529, 48},
        {1530, 40},
        {1532, 32},
        {1534, 24},
        {1536, 16},
        {1538, 8},
        {1542, 0},
        {1554, 56},
    }
    _pcsp__left_shift = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {402, 24},
        {403, 16},
        {405, 8},
        {406, 0},
        {414, 24},
        {415, 16},
        {417, 8},
        {418, 0},
        {539, 24},
    }
    _pcsp__right_shift = [][2]uint32{
        {1, 0},
        {4, 8},
        {436, 16},
        {437, 8},
        {438, 0},
        {446, 16},
        {447, 8},
        {448, 0},
        {456, 16},
        {457, 8},
        {459, 0},
    }
    _pcsp__j2t_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {643, 72},
        {647, 48},
        {648, 40},
        {650, 32},
        {652, 24},
        {654, 16},
        {656, 8},
        {660, 0},
        {869, 72},
    }
    _pcsp__unquote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1799, 104},
        {1803, 48},
        {1804, 40},
        {1806, 32},
        {1808, 24},
        {1810, 16},
        {1812, 8},
        {1816, 0},
        {2361, 104},
    }
    _pcsp__unhex16_is = [][2]uint32{
        {1, 0},
        {35, 8},
        {36, 0},
        {62, 8},
        {63, 0},
        {97, 8},
        {98, 0},
        {121, 8},
        {123, 0},
    }
    _pcsp__j2t_binary = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {179, 72},
        {183, 48},
        {184, 40},
        {186, 32},
        {188, 24},
        {190, 16},
        {192, 8},
        {193, 0},
        {221, 72},
    }
    _pcsp__b64decode = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {2840, 144},
        {2844, 48},
        {2845, 40},
        {2847, 32},
        {2849, 24},
        {2851, 16},
        {2853, 8},
        {2858, 0},
    }
    _pcsp__j2t_field_vm = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {342, 72},
        {346, 48},
        {347, 40},
        {349, 32},
        {351, 24},
        {353, 16},
        {355, 8},
        {356, 0},
        {673, 72},
        {677, 48},
        {678, 40},
        {680, 32},
        {682, 24},
        {684, 16},
        {686, 8},
        {687, 0},
        {777, 72},
        {781, 48},
        {782, 40},
        {784, 32},
        {786, 24},
        {788, 16},
        {790, 8},
        {791, 0},
        {1124, 72},
    }
    _pcsp__tb_write_string = [][2]uint32{
        {1, 0},
        {45, 8},
        {46, 0},
        {275, 8},
        {279, 0},
        {627, 8},
        {631, 0},
        {649, 8},
    }
    _pcsp__tb_write_default_or_empty = [][2]uint32{
        {1, 0},
        {4, 8},
        {319, 16},
        {320, 8},
        {324, 0},
        {363, 16},
        {364, 8},
        {365, 0},
        {464, 16},
        {465, 8},
        {466, 0},
        {482, 16},
        {483, 8},
        {484, 0},
        {588, 16},
        {589, 8},
        {590, 0},
        {607, 16},
        {608, 8},
        {609, 0},
        {930, 16},
        {931, 8},
        {936, 0},
    }
    _pcsp__j2t_write_unset_fields = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {571, 104},
        {575, 48},
        {576, 40},
        {578, 32},
        {580, 24},
        {582, 16},
        {584, 8},
        {585, 0},
        {652, 104},
    }
    _pcsp__j2t_key = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1716, 104},
        {1720, 48},
        {1721, 40},
        {1723, 32},
        {1725, 24},
        {1727, 16},
        {1729, 8},
        {1733, 0},
        {1957, 104},
    }
    _pcsp__j2t_find_field_key = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {349, 40},
        {350, 32},
        {352, 24},
        {354, 16},
        {356, 8},
        {357, 0},
        {361, 40},
        {362, 32},
        {364, 24},
        {366, 16},
        {368, 8},
        {374, 0},
    }
    _pcsp__quote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {2664, 72},
        {2668, 48},
        {2669, 40},
        {2671, 32},
        {2673, 24},
        {2675, 16},
        {2677, 8},
        {2681, 0},
        {2712, 72},
    }
    _pcsp__tb_skip = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {947, 48},
        {948, 40},
        {950, 32},
        {952, 24},
        {954, 16},
        {956, 8},
        {957, 0},
        {972, 48},
    }
    _pcsp__tb_write_i64 = [][2]uint32{
        {1, 0},
        {33, 8},
        {34, 0},
        {51, 8},
        {53, 0},
    }
    _pcsp__trie_get = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {323, 32},
        {324, 24},
        {326, 16},
        {328, 8},
        {330, 0},
    }
)

var Funcs = []loader.CFunc{
    {"__native_entry__", 0, 67, 0, nil},
    {"_f64toa", _entry__f64toa, _size__f64toa, _stack__f64toa, _pcsp__f64toa},
    {"_format_significand", _entry__format_significand, _size__format_significand, _stack__format_significand, _pcsp__format_significand},
    {"_format_integer", _entry__format_integer, _size__format_integer, _stack__format_integer, _pcsp__format_integer},
    {"_hm_get", _entry__hm_get, _size__hm_get, _stack__hm_get, _pcsp__hm_get},
    {"_i64toa", _entry__i64toa, _size__i64toa, _stack__i64toa, _pcsp__i64toa},
    {"_u64toa", _entry__u64toa, _size__u64toa, _stack__u64toa, _pcsp__u64toa},
    {"_j2t_fsm_exec", _entry__j2t_fsm_exec, _size__j2t_fsm_exec, _stack__j2t_fsm_exec, _pcsp__j2t_fsm_exec},
    {"_advance_ns", _entry__advance_ns, _size__advance_ns, _stack__advance_ns, _pcsp__advance_ns},
    {"_fsm_exec", _entry__fsm_exec, _size__fsm_exec, _stack__fsm_exec, _pcsp__fsm_exec},
    {"_advance_string", _entry__advance_string, _size__advance_string, _stack__advance_string, _pcsp__advance_string},
    {"_validate_string", _entry__validate_string, _size__validate_string, _stack__validate_string, _pcsp__validate_string},
    {"_utf8_validate", _entry__utf8_validate, _size__utf8_validate, _stack__utf8_validate, _pcsp__utf8_validate},
    {"_skip_number", _entry__skip_number, _size__skip_number, _stack__skip_number, _pcsp__skip_number},
    {"_j2t_number", _entry__j2t_number, _size__j2t_number, _stack__j2t_number, _pcsp__j2t_number},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
    {"_atof_eisel_lemire64", _entry__atof_eisel_lemire64, _size__atof_eisel_lemire64, _stack__atof_eisel_lemire64, _pcsp__atof_eisel_lemire64},
    {"_atof_native", _entry__atof_native, _size__atof_native, _stack__atof_native, _pcsp__atof_native},
    {"_decimal_to_f64", _entry__decimal_to_f64, _size__decimal_to_f64, _stack__decimal_to_f64, _pcsp__decimal_to_f64},
    {"_left_shift", _entry__left_shift, _size__left_shift, _stack__left_shift, _pcsp__left_shift},
    {"_right_shift", _entry__right_shift, _size__right_shift, _stack__right_shift, _pcsp__right_shift},
    {"_j2t_string", _entry__j2t_string, _size__j2t_string, _stack__j2t_string, _pcsp__j2t_string},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
    {"_unhex16_is", _entry__unhex16_is, _size__unhex16_is, _stack__unhex16_is, _pcsp__unhex16_is},
    {"_j2t_binary", _entry__j2t_binary, _size__j2t_binary, _stack__j2t_binary, _pcsp__j2t_binary},
    {"_b64decode", _entry__b64decode, _size__b64decode, _stack__b64decode, _pcsp__b64decode},
    {"_j2t_field_vm", _entry__j2t_field_vm, _size__j2t_field_vm, _stack__j2t_field_vm, _pcsp__j2t_field_vm},
    {"_tb_write_string", _entry__tb_write_string, _size__tb_write_string, _stack__tb_write_string, _pcsp__tb_write_string},
    {"_tb_write_default_or_empty", _entry__tb_write_default_or_empty, _size__tb_write_default_or_empty, _stack__tb_write_default_or_empty, _pcsp__tb_write_default_or_empty},
    {"_j2t_write_unset_fields", _entry__j2t_write_unset_fields, _size__j2t_write_unset_fields, _stack__j2t_write_unset_fields, _pcsp__j2t_write_unset_fields},
    {"_j2t_key", _entry__j2t_key, _size__j2t_key, _stack__j2t_key, _pcsp__j2t_key},
    {"_j2t_find_field_key", _entry__j2t_find_field_key, _size__j2t_find_field_key, _stack__j2t_find_field_key, _pcsp__j2t_find_field_key},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
    {"_tb_skip", _entry__tb_skip, _size__tb_skip, _stack__tb_skip, _pcsp__tb_skip},
    {"_tb_write_i64", _entry__tb_write_i64, _size__tb_write_i64, _stack__tb_write_i64, _pcsp__tb_write_i64},
    {"_trie_get", _entry__trie_get, _size__trie_get, _stack__trie_get, _pcsp__trie_get},
}
