// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__f64toa       uintptr = __native_entry__() + 752
    _subr__hm_get       uintptr = __native_entry__() + 33568
    _subr__html_escape  uintptr = __native_entry__() + 11552
    _subr__i64toa       uintptr = __native_entry__() + 4384
    _subr__j2t_fsm_exec uintptr = __native_entry__() + 44800
    _subr__lspace       uintptr = __native_entry__() + 224
    _subr__quote        uintptr = __native_entry__() + 6096
    _subr__skip_array   uintptr = __native_entry__() + 25904
    _subr__skip_object  uintptr = __native_entry__() + 25968
    _subr__skip_one     uintptr = __native_entry__() + 24000
    _subr__tb_skip      uintptr = __native_entry__() + 53360
    _subr__tb_write_i64 uintptr = __native_entry__() + 35184
    _subr__trie_get     uintptr = __native_entry__() + 34432
    _subr__u64toa       uintptr = __native_entry__() + 4624
    _subr__unquote      uintptr = __native_entry__() + 8848
    _subr__validate_one uintptr = __native_entry__() + 28000
    _subr__value        uintptr = __native_entry__() + 17696
    _subr__vnumber      uintptr = __native_entry__() + 19968
    _subr__vsigned      uintptr = __native_entry__() + 21552
    _subr__vstring      uintptr = __native_entry__() + 18928
    _subr__vunsigned    uintptr = __native_entry__() + 21904
)

const (
    _stack__f64toa = 80
    _stack__hm_get = 24
    _stack__html_escape = 72
    _stack__i64toa = 16
    _stack__j2t_fsm_exec = 624
    _stack__lspace = 8
    _stack__quote = 72
    _stack__skip_array = 184
    _stack__skip_object = 184
    _stack__skip_one = 184
    _stack__tb_skip = 48
    _stack__tb_write_i64 = 8
    _stack__trie_get = 32
    _stack__u64toa = 8
    _stack__unquote = 128
    _stack__validate_one = 184
    _stack__value = 360
    _stack__vnumber = 288
    _stack__vsigned = 16
    _stack__vstring = 104
    _stack__vunsigned = 24
)

var (
    _ = _subr__f64toa
    _ = _subr__hm_get
    _ = _subr__html_escape
    _ = _subr__i64toa
    _ = _subr__j2t_fsm_exec
    _ = _subr__lspace
    _ = _subr__quote
    _ = _subr__skip_array
    _ = _subr__skip_object
    _ = _subr__skip_one
    _ = _subr__tb_skip
    _ = _subr__tb_write_i64
    _ = _subr__trie_get
    _ = _subr__u64toa
    _ = _subr__unquote
    _ = _subr__validate_one
    _ = _subr__value
    _ = _subr__vnumber
    _ = _subr__vsigned
    _ = _subr__vstring
    _ = _subr__vunsigned
)

const (
    _ = _stack__f64toa
    _ = _stack__hm_get
    _ = _stack__html_escape
    _ = _stack__i64toa
    _ = _stack__j2t_fsm_exec
    _ = _stack__lspace
    _ = _stack__quote
    _ = _stack__skip_array
    _ = _stack__skip_object
    _ = _stack__skip_one
    _ = _stack__tb_skip
    _ = _stack__tb_write_i64
    _ = _stack__trie_get
    _ = _stack__u64toa
    _ = _stack__unquote
    _ = _stack__validate_one
    _ = _stack__value
    _ = _stack__vnumber
    _ = _stack__vsigned
    _ = _stack__vstring
    _ = _stack__vunsigned
)
