// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package example5

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/cloudwego/dynamicgo/testdata/kitex_gen/base"
)

type FOO int64

const (
	FOO_A FOO = 1
)

func (p FOO) String() string {
	switch p {
	case FOO_A:
		return "A"
	}
	return "<UNSET>"
}

func FOOFromString(s string) (FOO, error) {
	switch s {
	case "A":
		return FOO_A, nil
	}
	return FOO(0), fmt.Errorf("not a valid FOO string")
}

func FOOPtr(v FOO) *FOO { return &v }
func (p *FOO) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = FOO(result.Int64)
	return
}

func (p *FOO) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type InnerBase struct {
	Bool               bool                  `thrift:"Bool,1" frugal:"1,default,bool" json:"Bool"`
	Int32              int32                 `thrift:"Int32,4" frugal:"4,default,i32" json:"Int32"`
	Int64              int64                 `thrift:"Int64,5" frugal:"5,default,i64" json:"Int64"`
	Double             float64               `thrift:"Double,6" frugal:"6,default,double" json:"Double"`
	String_            string                `thrift:"String,7" frugal:"7,default,string" json:"String"`
	ListString         []string              `thrift:"ListString,8" frugal:"8,default,list<string>" json:"ListString"`
	MapStringString    map[string]string     `thrift:"MapStringString,9" frugal:"9,default,map<string:string>" json:"MapStringString"`
	SetInt32_          []int32               `thrift:"SetInt32,10" frugal:"10,default,set<i32>" json:"SetInt32"`
	MapInt32String     map[int32]string      `thrift:"MapInt32String,12" frugal:"12,default,map<i32:string>" json:"MapInt32String"`
	Binary             []byte                `thrift:"Binary,13" frugal:"13,default,binary" json:"Binary"`
	MapInt64String     map[int64]string      `thrift:"MapInt64String,16" frugal:"16,default,map<i64:string>" json:"MapInt64String"`
	ListInnerBase      []*InnerBase          `thrift:"ListInnerBase,18" frugal:"18,default,list<InnerBase>" json:"ListInnerBase"`
	MapStringInnerBase map[string]*InnerBase `thrift:"MapStringInnerBase,19" frugal:"19,default,map<string:InnerBase>" json:"MapStringInnerBase"`
	Base               *base.Base            `thrift:"Base,255" frugal:"255,default,base.Base" json:"Base"`
}

func NewInnerBase() *InnerBase {
	return &InnerBase{}
}

func (p *InnerBase) InitDefault() {
}

func (p *InnerBase) GetBool() (v bool) {
	return p.Bool
}

func (p *InnerBase) GetInt32() (v int32) {
	return p.Int32
}

func (p *InnerBase) GetInt64() (v int64) {
	return p.Int64
}

func (p *InnerBase) GetDouble() (v float64) {
	return p.Double
}

func (p *InnerBase) GetString() (v string) {
	return p.String_
}

func (p *InnerBase) GetListString() (v []string) {
	return p.ListString
}

func (p *InnerBase) GetMapStringString() (v map[string]string) {
	return p.MapStringString
}

func (p *InnerBase) GetSetInt32() (v []int32) {
	return p.SetInt32_
}

func (p *InnerBase) GetMapInt32String() (v map[int32]string) {
	return p.MapInt32String
}

func (p *InnerBase) GetBinary() (v []byte) {
	return p.Binary
}

func (p *InnerBase) GetMapInt64String() (v map[int64]string) {
	return p.MapInt64String
}

func (p *InnerBase) GetListInnerBase() (v []*InnerBase) {
	return p.ListInnerBase
}

func (p *InnerBase) GetMapStringInnerBase() (v map[string]*InnerBase) {
	return p.MapStringInnerBase
}

var InnerBase_Base_DEFAULT *base.Base

func (p *InnerBase) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return InnerBase_Base_DEFAULT
	}
	return p.Base
}
func (p *InnerBase) SetBool(val bool) {
	p.Bool = val
}
func (p *InnerBase) SetInt32(val int32) {
	p.Int32 = val
}
func (p *InnerBase) SetInt64(val int64) {
	p.Int64 = val
}
func (p *InnerBase) SetDouble(val float64) {
	p.Double = val
}
func (p *InnerBase) SetString(val string) {
	p.String_ = val
}
func (p *InnerBase) SetListString(val []string) {
	p.ListString = val
}
func (p *InnerBase) SetMapStringString(val map[string]string) {
	p.MapStringString = val
}
func (p *InnerBase) SetSetInt32(val []int32) {
	p.SetInt32_ = val
}
func (p *InnerBase) SetMapInt32String(val map[int32]string) {
	p.MapInt32String = val
}
func (p *InnerBase) SetBinary(val []byte) {
	p.Binary = val
}
func (p *InnerBase) SetMapInt64String(val map[int64]string) {
	p.MapInt64String = val
}
func (p *InnerBase) SetListInnerBase(val []*InnerBase) {
	p.ListInnerBase = val
}
func (p *InnerBase) SetMapStringInnerBase(val map[string]*InnerBase) {
	p.MapStringInnerBase = val
}
func (p *InnerBase) SetBase(val *base.Base) {
	p.Base = val
}

func (p *InnerBase) IsSetBase() bool {
	return p.Base != nil
}

func (p *InnerBase) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InnerBase(%+v)", *p)
}

var fieldIDToName_InnerBase = map[int16]string{
	1:   "Bool",
	4:   "Int32",
	5:   "Int64",
	6:   "Double",
	7:   "String",
	8:   "ListString",
	9:   "MapStringString",
	10:  "SetInt32",
	12:  "MapInt32String",
	13:  "Binary",
	16:  "MapInt64String",
	18:  "ListInnerBase",
	19:  "MapStringInnerBase",
	255: "Base",
}

type ExampleService interface {
	ExampleMethod(ctx context.Context, req *InnerBase) (r *InnerBase, err error)
}

type ExampleServiceExampleMethodArgs struct {
	Req *InnerBase `thrift:"req,1" frugal:"1,default,InnerBase" json:"req"`
}

func NewExampleServiceExampleMethodArgs() *ExampleServiceExampleMethodArgs {
	return &ExampleServiceExampleMethodArgs{}
}

func (p *ExampleServiceExampleMethodArgs) InitDefault() {
}

var ExampleServiceExampleMethodArgs_Req_DEFAULT *InnerBase

func (p *ExampleServiceExampleMethodArgs) GetReq() (v *InnerBase) {
	if !p.IsSetReq() {
		return ExampleServiceExampleMethodArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ExampleServiceExampleMethodArgs) SetReq(val *InnerBase) {
	p.Req = val
}

func (p *ExampleServiceExampleMethodArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExampleServiceExampleMethodArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExampleServiceExampleMethodArgs(%+v)", *p)
}

var fieldIDToName_ExampleServiceExampleMethodArgs = map[int16]string{
	1: "req",
}

type ExampleServiceExampleMethodResult struct {
	Success *InnerBase `thrift:"success,0,optional" frugal:"0,optional,InnerBase" json:"success,omitempty"`
}

func NewExampleServiceExampleMethodResult() *ExampleServiceExampleMethodResult {
	return &ExampleServiceExampleMethodResult{}
}

func (p *ExampleServiceExampleMethodResult) InitDefault() {
}

var ExampleServiceExampleMethodResult_Success_DEFAULT *InnerBase

func (p *ExampleServiceExampleMethodResult) GetSuccess() (v *InnerBase) {
	if !p.IsSetSuccess() {
		return ExampleServiceExampleMethodResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ExampleServiceExampleMethodResult) SetSuccess(x interface{}) {
	p.Success = x.(*InnerBase)
}

func (p *ExampleServiceExampleMethodResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExampleServiceExampleMethodResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExampleServiceExampleMethodResult(%+v)", *p)
}

var fieldIDToName_ExampleServiceExampleMethodResult = map[int16]string{
	0: "success",
}
