// Code generated by Kitex v0.7.2. DO NOT EDIT.
package testservice2

import (
	example2 "github.com/cloudwego/dynamicgo/testdata/kitex_gen/pb/example2"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler example2.TestService2, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
