// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f64toa = 464
    _entry__format_significand = 47984
    _entry__format_integer = 3616
    _entry__hm_get = 27808
    _entry__i64toa = 4048
    _entry__u64toa = 4320
    _entry__j2t_fsm_exec = 38480
    _entry__advance_ns = 13472
    _entry__fsm_exec = 20192
    _entry__advance_string = 15632
    _entry__validate_string = 22320
    _entry__utf8_validate = 23760
    _entry__skip_number = 19104
    _entry__j2t_number = 34256
    _entry__vnumber = 16624
    _entry__atof_eisel_lemire64 = 11408
    _entry__atof_native = 12800
    _entry__decimal_to_f64 = 11808
    _entry__left_shift = 48464
    _entry__right_shift = 49008
    _entry__j2t_string = 34848
    _entry__unquote = 7584
    _entry__unhex16_is = 9920
    _entry__j2t_binary = 35680
    _entry__b64decode = 25120
    _entry__j2t_field_vm = 37280
    _entry__tb_write_string = 29536
    _entry__tb_write_default_or_empty = 31424
    _entry__j2t_write_unset_fields = 33600
    _entry__j2t_find_field_key = 36608
    _entry__quote = 5808
    _entry__tb_skip = 46928
    _entry__tb_write_i64 = 29408
    _entry__trie_get = 28640
)

const (
    _stack__f64toa = 80
    _stack__format_significand = 24
    _stack__format_integer = 16
    _stack__hm_get = 24
    _stack__i64toa = 16
    _stack__u64toa = 8
    _stack__j2t_fsm_exec = 584
    _stack__advance_ns = 8
    _stack__fsm_exec = 224
    _stack__advance_string = 56
    _stack__validate_string = 136
    _stack__utf8_validate = 32
    _stack__skip_number = 32
    _stack__j2t_number = 320
    _stack__vnumber = 264
    _stack__atof_eisel_lemire64 = 40
    _stack__atof_native = 144
    _stack__decimal_to_f64 = 88
    _stack__left_shift = 32
    _stack__right_shift = 16
    _stack__j2t_string = 184
    _stack__unquote = 112
    _stack__unhex16_is = 8
    _stack__j2t_binary = 216
    _stack__b64decode = 144
    _stack__j2t_field_vm = 336
    _stack__tb_write_string = 24
    _stack__tb_write_default_or_empty = 16
    _stack__j2t_write_unset_fields = 120
    _stack__j2t_find_field_key = 64
    _stack__quote = 80
    _stack__tb_skip = 48
    _stack__tb_write_i64 = 8
    _stack__trie_get = 32
)

const (
    _size__f64toa = 3152
    _size__format_significand = 480
    _size__format_integer = 432
    _size__hm_get = 496
    _size__i64toa = 272
    _size__u64toa = 1440
    _size__j2t_fsm_exec = 7920
    _size__advance_ns = 608
    _size__fsm_exec = 1340
    _size__advance_string = 944
    _size__validate_string = 1440
    _size__utf8_validate = 428
    _size__skip_number = 908
    _size__j2t_number = 548
    _size__vnumber = 1648
    _size__atof_eisel_lemire64 = 400
    _size__atof_native = 608
    _size__decimal_to_f64 = 992
    _size__left_shift = 544
    _size__right_shift = 480
    _size__j2t_string = 832
    _size__unquote = 2336
    _size__unhex16_is = 128
    _size__j2t_binary = 224
    _size__b64decode = 1888
    _size__j2t_field_vm = 1120
    _size__tb_write_string = 608
    _size__tb_write_default_or_empty = 900
    _size__j2t_write_unset_fields = 656
    _size__j2t_find_field_key = 384
    _size__quote = 1760
    _size__tb_skip = 972
    _size__tb_write_i64 = 64
    _size__trie_get = 336
)

var (
    _pcsp__f64toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {3033, 56},
        {3037, 48},
        {3038, 40},
        {3040, 32},
        {3042, 24},
        {3044, 16},
        {3046, 8},
        {3047, 0},
        {3138, 56},
    }
    _pcsp__format_significand = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {468, 24},
        {469, 16},
        {471, 8},
        {473, 0},
    }
    _pcsp__format_integer = [][2]uint32{
        {1, 0},
        {4, 8},
        {412, 16},
        {413, 8},
        {414, 0},
        {423, 16},
        {424, 8},
        {426, 0},
    }
    _pcsp__hm_get = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {339, 24},
        {340, 16},
        {342, 8},
        {344, 0},
        {483, 24},
    }
    _pcsp__i64toa = [][2]uint32{
        {1, 0},
        {171, 8},
        {172, 0},
        {207, 8},
        {208, 0},
        {222, 8},
        {223, 0},
        {247, 8},
        {248, 0},
        {253, 8},
        {259, 0},
    }
    _pcsp__u64toa = [][2]uint32{
        {13, 0},
        {162, 8},
        {163, 0},
        {175, 8},
        {240, 0},
        {498, 8},
        {499, 0},
        {519, 8},
        {608, 0},
        {882, 8},
        {976, 0},
        {1434, 8},
        {1436, 0},
    }
    _pcsp__j2t_fsm_exec = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {6530, 248},
        {6537, 48},
        {6538, 40},
        {6540, 32},
        {6542, 24},
        {6544, 16},
        {6546, 8},
        {6547, 0},
        {7920, 248},
    }
    _pcsp__advance_ns = [][2]uint32{
        {1, 0},
        {585, 8},
        {586, 0},
        {592, 8},
        {593, 0},
        {605, 8},
    }
    _pcsp__fsm_exec = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1324, 88},
        {1328, 48},
        {1329, 40},
        {1331, 32},
        {1333, 24},
        {1335, 16},
        {1337, 8},
        {1340, 0},
    }
    _pcsp__advance_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {402, 56},
        {406, 48},
        {407, 40},
        {409, 32},
        {411, 24},
        {413, 16},
        {415, 8},
        {416, 0},
        {936, 56},
    }
    _pcsp__validate_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {681, 104},
        {685, 48},
        {686, 40},
        {688, 32},
        {690, 24},
        {692, 16},
        {694, 8},
        {695, 0},
        {1426, 104},
    }
    _pcsp__utf8_validate = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {418, 32},
        {419, 24},
        {421, 16},
        {423, 8},
        {428, 0},
    }
    _pcsp__skip_number = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {771, 32},
        {772, 24},
        {774, 16},
        {776, 8},
        {777, 0},
        {908, 32},
    }
    _pcsp__j2t_number = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {531, 56},
        {535, 48},
        {536, 40},
        {538, 32},
        {540, 24},
        {542, 16},
        {544, 8},
        {548, 0},
    }
    _pcsp__vnumber = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {147, 120},
        {151, 48},
        {152, 40},
        {154, 32},
        {156, 24},
        {158, 16},
        {160, 8},
        {161, 0},
        {1642, 120},
    }
    _pcsp__atof_eisel_lemire64 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {315, 40},
        {316, 32},
        {318, 24},
        {320, 16},
        {322, 8},
        {323, 0},
        {387, 40},
    }
    _pcsp__atof_native = [][2]uint32{
        {1, 0},
        {4, 8},
        {596, 56},
        {600, 8},
        {602, 0},
    }
    _pcsp__decimal_to_f64 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {951, 56},
        {955, 48},
        {956, 40},
        {958, 32},
        {960, 24},
        {962, 16},
        {964, 8},
        {965, 0},
        {977, 56},
    }
    _pcsp__left_shift = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {418, 32},
        {419, 24},
        {421, 16},
        {423, 8},
        {424, 0},
        {539, 32},
    }
    _pcsp__right_shift = [][2]uint32{
        {1, 0},
        {4, 8},
        {452, 16},
        {453, 8},
        {454, 0},
        {462, 16},
        {463, 8},
        {464, 0},
        {472, 16},
        {473, 8},
        {475, 0},
    }
    _pcsp__j2t_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {386, 72},
        {390, 48},
        {391, 40},
        {393, 32},
        {395, 24},
        {397, 16},
        {399, 8},
        {400, 0},
        {824, 72},
    }
    _pcsp__unquote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1614, 104},
        {1618, 48},
        {1619, 40},
        {1621, 32},
        {1623, 24},
        {1625, 16},
        {1627, 8},
        {1628, 0},
        {2329, 104},
    }
    _pcsp__unhex16_is = [][2]uint32{
        {1, 0},
        {35, 8},
        {36, 0},
        {62, 8},
        {63, 0},
        {97, 8},
        {98, 0},
        {121, 8},
        {123, 0},
    }
    _pcsp__j2t_binary = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {179, 72},
        {183, 48},
        {184, 40},
        {186, 32},
        {188, 24},
        {190, 16},
        {192, 8},
        {193, 0},
        {221, 72},
    }
    _pcsp__b64decode = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1858, 144},
        {1862, 48},
        {1863, 40},
        {1865, 32},
        {1867, 24},
        {1869, 16},
        {1871, 8},
        {1873, 0},
    }
    _pcsp__j2t_field_vm = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {340, 72},
        {344, 48},
        {345, 40},
        {347, 32},
        {349, 24},
        {351, 16},
        {353, 8},
        {354, 0},
        {671, 72},
        {675, 48},
        {676, 40},
        {678, 32},
        {680, 24},
        {682, 16},
        {684, 8},
        {685, 0},
        {775, 72},
        {779, 48},
        {780, 40},
        {782, 32},
        {784, 24},
        {786, 16},
        {788, 8},
        {789, 0},
        {1120, 72},
    }
    _pcsp__tb_write_string = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {194, 24},
        {195, 16},
        {197, 8},
        {198, 0},
        {271, 24},
        {272, 16},
        {274, 8},
        {275, 0},
        {595, 24},
    }
    _pcsp__tb_write_default_or_empty = [][2]uint32{
        {1, 0},
        {4, 8},
        {319, 16},
        {320, 8},
        {321, 0},
        {360, 16},
        {361, 8},
        {362, 0},
        {458, 16},
        {459, 8},
        {460, 0},
        {476, 16},
        {477, 8},
        {478, 0},
        {582, 16},
        {583, 8},
        {584, 0},
        {601, 16},
        {602, 8},
        {603, 0},
        {896, 16},
        {897, 8},
        {900, 0},
    }
    _pcsp__j2t_write_unset_fields = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {571, 104},
        {575, 48},
        {576, 40},
        {578, 32},
        {580, 24},
        {582, 16},
        {584, 8},
        {585, 0},
        {652, 104},
    }
    _pcsp__j2t_find_field_key = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {349, 40},
        {350, 32},
        {352, 24},
        {354, 16},
        {356, 8},
        {357, 0},
        {361, 40},
        {362, 32},
        {364, 24},
        {366, 16},
        {368, 8},
        {374, 0},
    }
    _pcsp__quote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1701, 80},
        {1705, 48},
        {1706, 40},
        {1708, 32},
        {1710, 24},
        {1712, 16},
        {1714, 8},
        {1715, 0},
        {1750, 80},
    }
    _pcsp__tb_skip = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {947, 48},
        {948, 40},
        {950, 32},
        {952, 24},
        {954, 16},
        {956, 8},
        {957, 0},
        {972, 48},
    }
    _pcsp__tb_write_i64 = [][2]uint32{
        {1, 0},
        {33, 8},
        {34, 0},
        {51, 8},
        {53, 0},
    }
    _pcsp__trie_get = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {323, 32},
        {324, 24},
        {326, 16},
        {328, 8},
        {330, 0},
    }
)

var Funcs = []loader.CFunc{
    {"__native_entry__", 0, 67, 0, nil},
    {"_f64toa", _entry__f64toa, _size__f64toa, _stack__f64toa, _pcsp__f64toa},
    {"_format_significand", _entry__format_significand, _size__format_significand, _stack__format_significand, _pcsp__format_significand},
    {"_format_integer", _entry__format_integer, _size__format_integer, _stack__format_integer, _pcsp__format_integer},
    {"_hm_get", _entry__hm_get, _size__hm_get, _stack__hm_get, _pcsp__hm_get},
    {"_i64toa", _entry__i64toa, _size__i64toa, _stack__i64toa, _pcsp__i64toa},
    {"_u64toa", _entry__u64toa, _size__u64toa, _stack__u64toa, _pcsp__u64toa},
    {"_j2t_fsm_exec", _entry__j2t_fsm_exec, _size__j2t_fsm_exec, _stack__j2t_fsm_exec, _pcsp__j2t_fsm_exec},
    {"_advance_ns", _entry__advance_ns, _size__advance_ns, _stack__advance_ns, _pcsp__advance_ns},
    {"_fsm_exec", _entry__fsm_exec, _size__fsm_exec, _stack__fsm_exec, _pcsp__fsm_exec},
    {"_advance_string", _entry__advance_string, _size__advance_string, _stack__advance_string, _pcsp__advance_string},
    {"_validate_string", _entry__validate_string, _size__validate_string, _stack__validate_string, _pcsp__validate_string},
    {"_utf8_validate", _entry__utf8_validate, _size__utf8_validate, _stack__utf8_validate, _pcsp__utf8_validate},
    {"_skip_number", _entry__skip_number, _size__skip_number, _stack__skip_number, _pcsp__skip_number},
    {"_j2t_number", _entry__j2t_number, _size__j2t_number, _stack__j2t_number, _pcsp__j2t_number},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
    {"_atof_eisel_lemire64", _entry__atof_eisel_lemire64, _size__atof_eisel_lemire64, _stack__atof_eisel_lemire64, _pcsp__atof_eisel_lemire64},
    {"_atof_native", _entry__atof_native, _size__atof_native, _stack__atof_native, _pcsp__atof_native},
    {"_decimal_to_f64", _entry__decimal_to_f64, _size__decimal_to_f64, _stack__decimal_to_f64, _pcsp__decimal_to_f64},
    {"_left_shift", _entry__left_shift, _size__left_shift, _stack__left_shift, _pcsp__left_shift},
    {"_right_shift", _entry__right_shift, _size__right_shift, _stack__right_shift, _pcsp__right_shift},
    {"_j2t_string", _entry__j2t_string, _size__j2t_string, _stack__j2t_string, _pcsp__j2t_string},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
    {"_unhex16_is", _entry__unhex16_is, _size__unhex16_is, _stack__unhex16_is, _pcsp__unhex16_is},
    {"_j2t_binary", _entry__j2t_binary, _size__j2t_binary, _stack__j2t_binary, _pcsp__j2t_binary},
    {"_b64decode", _entry__b64decode, _size__b64decode, _stack__b64decode, _pcsp__b64decode},
    {"_j2t_field_vm", _entry__j2t_field_vm, _size__j2t_field_vm, _stack__j2t_field_vm, _pcsp__j2t_field_vm},
    {"_tb_write_string", _entry__tb_write_string, _size__tb_write_string, _stack__tb_write_string, _pcsp__tb_write_string},
    {"_tb_write_default_or_empty", _entry__tb_write_default_or_empty, _size__tb_write_default_or_empty, _stack__tb_write_default_or_empty, _pcsp__tb_write_default_or_empty},
    {"_j2t_write_unset_fields", _entry__j2t_write_unset_fields, _size__j2t_write_unset_fields, _stack__j2t_write_unset_fields, _pcsp__j2t_write_unset_fields},
    {"_j2t_find_field_key", _entry__j2t_find_field_key, _size__j2t_find_field_key, _stack__j2t_find_field_key, _pcsp__j2t_find_field_key},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
    {"_tb_skip", _entry__tb_skip, _size__tb_skip, _stack__tb_skip, _pcsp__tb_skip},
    {"_tb_write_i64", _entry__tb_write_i64, _size__tb_write_i64, _stack__tb_write_i64, _pcsp__tb_write_i64},
    {"_trie_get", _entry__trie_get, _size__trie_get, _stack__trie_get, _pcsp__trie_get},
}
