name: Benchmark Linux-X64

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Benchmark
        run: |
          cd testdata/test
          go mod tidy
          go test -benchmem -run=^$ -bench . -benchtime=100ms
