name: Push Check Linux-X64

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
    runs-on: [ARM64, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Unit Test
        run: |
          go test -race ./...
