name: Push Check Linux-X64

on: push

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Build native shared library
        run: |
          mkdir -p output && clang \
            -msse -mno-sse4 \
            -mavx -DUSE_AVX=1 \
            -mno-avx2 -DUSE_AVX2=0 \
            -ggdb3 -O0 \
            -DDEBUG=1 \
            -shared -fPIC -nostdlib \
            -mno-red-zone -fno-asynchronous-unwind-tables -fno-builtin \
            -fno-exceptions -fno-rtti -fno-stack-protector \
            -flto -fno-plt -fno-builtin-memcpy \
            -o output/libnative.so \
            -Inative \
            native/native.c

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # outdated native code, we need to use shared library
      # as we don't really generate them on CI.
      # - name: Unit Test
      #   run: |
      #     go test -race ./...

      - name: Unit Test shared lib
        run: |
          LD_LIBRARY_PATH=$PWD/output go test -race -tags sharedlib ./...