name: Push Check Linux-ARM64

on: push

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.20.x]
    runs-on: [ ARM64 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Test
        run: |
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/thrift
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/thrift/annotation
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/thrift/generic
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/conv/t2j
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/http
          GOARCH=arm64 go test -race -gcflags=all=-d=checkptr=0 github.com/cloudwego/dynamicgo/internal/json