name: Push Check Linux-X64

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-24.04-arm, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Unit Test
        run: |
          go test -race ./...

      - name: Testdata
        run: |
          cd testdata/test
          go mod tidy
          go test -race -v ./...
