// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Test Protobuf definitions with proto3 syntax.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: testdata/idl/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrafficEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=Open,proto3" json:"Open,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=Env,proto3" json:"Env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficEnv) Reset() {
	*x = TrafficEnv{}
	mi := &file_testdata_idl_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEnv) ProtoMessage() {}

func (x *TrafficEnv) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_idl_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEnv.ProtoReflect.Descriptor instead.
func (*TrafficEnv) Descriptor() ([]byte, []int) {
	return file_testdata_idl_base_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficEnv) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *TrafficEnv) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogID         string                 `protobuf:"bytes,1,opt,name=LogID,proto3" json:"LogID,omitempty"`
	Caller        string                 `protobuf:"bytes,2,opt,name=Caller,proto3" json:"Caller,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=Client,proto3" json:"Client,omitempty"`
	TrafficEnv    *TrafficEnv            `protobuf:"bytes,5,opt,name=TrafficEnv,proto3,oneof" json:"TrafficEnv,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=Extra,proto3" json:"Extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_testdata_idl_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_idl_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_testdata_idl_base_proto_rawDescGZIP(), []int{1}
}

func (x *Base) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *Base) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *Base) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Base) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Base) GetTrafficEnv() *TrafficEnv {
	if x != nil {
		return x.TrafficEnv
	}
	return nil
}

func (x *Base) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=StatusMessage,proto3" json:"StatusMessage,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=Extra,proto3" json:"Extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_testdata_idl_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_idl_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_testdata_idl_base_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BaseResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BaseResp) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_testdata_idl_base_proto protoreflect.FileDescriptor

const file_testdata_idl_base_proto_rawDesc = "" +
	"\n" +
	"\x17testdata/idl/base.proto\x12\x03pb3\"2\n" +
	"\n" +
	"TrafficEnv\x12\x12\n" +
	"\x04Open\x18\x01 \x01(\bR\x04Open\x12\x10\n" +
	"\x03Env\x18\x02 \x01(\tR\x03Env\"\x8b\x02\n" +
	"\x04Base\x12\x14\n" +
	"\x05LogID\x18\x01 \x01(\tR\x05LogID\x12\x16\n" +
	"\x06Caller\x18\x02 \x01(\tR\x06Caller\x12\x12\n" +
	"\x04Addr\x18\x03 \x01(\tR\x04Addr\x12\x16\n" +
	"\x06Client\x18\x04 \x01(\tR\x06Client\x124\n" +
	"\n" +
	"TrafficEnv\x18\x05 \x01(\v2\x0f.pb3.TrafficEnvH\x00R\n" +
	"TrafficEnv\x88\x01\x01\x12*\n" +
	"\x05Extra\x18\x06 \x03(\v2\x14.pb3.Base.ExtraEntryR\x05Extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_TrafficEnv\"\xba\x01\n" +
	"\bBaseResp\x12$\n" +
	"\rStatusMessage\x18\x01 \x01(\tR\rStatusMessage\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x02 \x01(\x05R\n" +
	"StatusCode\x12.\n" +
	"\x05Extra\x18\x03 \x03(\v2\x18.pb3.BaseResp.ExtraEntryR\x05Extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\tZ\apb/baseb\x06proto3"

var (
	file_testdata_idl_base_proto_rawDescOnce sync.Once
	file_testdata_idl_base_proto_rawDescData []byte
)

func file_testdata_idl_base_proto_rawDescGZIP() []byte {
	file_testdata_idl_base_proto_rawDescOnce.Do(func() {
		file_testdata_idl_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_idl_base_proto_rawDesc), len(file_testdata_idl_base_proto_rawDesc)))
	})
	return file_testdata_idl_base_proto_rawDescData
}

var file_testdata_idl_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testdata_idl_base_proto_goTypes = []any{
	(*TrafficEnv)(nil), // 0: pb3.TrafficEnv
	(*Base)(nil),       // 1: pb3.Base
	(*BaseResp)(nil),   // 2: pb3.BaseResp
	nil,                // 3: pb3.Base.ExtraEntry
	nil,                // 4: pb3.BaseResp.ExtraEntry
}
var file_testdata_idl_base_proto_depIdxs = []int32{
	0, // 0: pb3.Base.TrafficEnv:type_name -> pb3.TrafficEnv
	3, // 1: pb3.Base.Extra:type_name -> pb3.Base.ExtraEntry
	4, // 2: pb3.BaseResp.Extra:type_name -> pb3.BaseResp.ExtraEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_testdata_idl_base_proto_init() }
func file_testdata_idl_base_proto_init() {
	if File_testdata_idl_base_proto != nil {
		return
	}
	file_testdata_idl_base_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_idl_base_proto_rawDesc), len(file_testdata_idl_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_idl_base_proto_goTypes,
		DependencyIndexes: file_testdata_idl_base_proto_depIdxs,
		MessageInfos:      file_testdata_idl_base_proto_msgTypes,
	}.Build()
	File_testdata_idl_base_proto = out.File
	file_testdata_idl_base_proto_goTypes = nil
	file_testdata_idl_base_proto_depIdxs = nil
}
